name: C++ CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your code from the repository

    - name: Set up C++ compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ # Install g++ compiler

    - name: Compile C++ code
      run: |
        g++ signin.cpp -o signin # Compile signin.cpp into an executable named 'signin'

    - name: Run tests (optional)
      run: |
        # This is a placeholder for running tests.
        # If you have a separate test file (e.g., test_signin.cpp), you would compile and run it here.
        # For a simple signin.cpp, you might just run the compiled program with some test inputs.
        echo "Running a basic test..."
        ./signin <<< "testuser testpass" # Example: provide input to your signin program
        echo "Test completed."

  deploy:
    needs: build_and_test # This job depends on the successful completion of the build_and_test job
    runs-on: ubuntu-latest
    environment: production # Define an environment for deployment (optional, but good practice)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy application (placeholder)
      run: |
        # This is a placeholder for your deployment steps.
        # The actual deployment steps will depend on where and how you want to deploy your application.
        # Examples include:
        # - Copying the executable to a server (e.g., using SCP)
        # - Building a Docker image and pushing it to a registry
        # - Deploying to a cloud service (e.g., AWS, Azure, Google Cloud)
        echo "Deploying the 'signin' application..."
        echo "Deployment steps go here. Replace with your actual deployment logic."
        # For example, if you're just copying the executable:
        # scp ./signin user@your-server:/path/to/deployment/directory/
        echo "Application deployed."
