name: Build and Test tictactoe

on:
  push:
    branches: [ main, dev, Game_Logic ]
  pull_request:
    branches: [ main, dev, Game_Logic ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Updated to v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y qtbase5-dev qt5-qmake cmake g++ build-essential
        sudo apt install -y libgl1-mesa-dev  # OpenGL dependency

    - name: Verify Source Files
      run: |
        ls -la Game_logic/tictactoe/
        echo "Checking for Board.h..."
        [ -f Game_logic/tictactoe/Board.h ] || exit 1

    - name: Configure with CMake
      working-directory: Game_logic/tictactoe
      run: |
        mkdir -p build
        cmake -B build -S .

    - name: Build
      working-directory: Game_logic/tictactoe/build
      run: cmake --build . --verbose  # Added verbose flag for better debugging

    - name: Run Tests
      working-directory: Game_logic/tictactoe/build
      run: |
        if [ -f "CTestTestfile.cmake" ]; then
          ctest --output-on-failure
        else
          echo "No tests found"
        fi