name: C++ Header/Module Check

on:
  push:
    branches: [ "first_AI_branch" ]
  pull_request:
    branches: [ "first_AI_branch" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: AI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install C++ build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Compile AI_Opponent.cpp (syntax check only)
        run: |
          g++ -std=c++11 -Wall -Wextra -c AI_Opponent.cpp
