name: CI for SessionManager.cpp

on:
  push:
    branches:
      - main  # or replace with your branch like 'Session_Management'
    paths:
      - 'SessionManager.cpp'

jobs:
  lint:
    name: Run Linter & Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python + cpplint
        run: |
          python3 -m pip install --upgrade pip
          pip install cpplint

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      # OPTIONAL: If you want to skip markdownlint errors completely
      - name: Disable markdownlint (dummy step)
        run: echo "Skipping markdownlint to avoid CLI version conflict"

      - name: Setup clang-format config
        run: |
          echo 'BasedOnStyle: Google' > .clang-format
          echo 'IndentWidth: 2' >> .clang-format
          echo 'ColumnLimit: 100' >> .clang-format
          echo 'SortIncludes: false' >> .clang-format
          echo 'AllowShortFunctionsOnASingleLine: Empty' >> .clang-format
          echo 'SpaceBeforeParens: ControlStatements' >> .clang-format

      - name: Run clang-format check
        run: clang-format --dry-run --Werror SessionManager.cpp

      - name: Run cpplint with filtered rules
        run: |
          cpplint \
            --filter=-whitespace/indent,-whitespace/braces,-runtime/references \
            SessionManager.cpp
