name: Lint SessionManager_DUT.cpp on Session_Management Branch

on:
  push:
    branches:
      - Session_Management
    paths:
      - 'SessionManager_DUT.cpp'

jobs:
  super-lint:
    name: Super Linter Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v5.0.0
        env:
          DEFAULT_BRANCH: Session_Management
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
