name: Lint SessionManager on Session_Management Branch

on:
  push:
    branches:
      - Session_Management
    paths:
      - 'SessionManager.cpp'
      - '.clang-format'
      - '**/*.md'      # if you also want to lint markdown on push
  pull_request:
    branches:
      - Session_Management
    paths:
      - 'SessionManager.cpp'
      - '.clang-format'
      - '**/*.md'

jobs:
  lint:
    name: Run clang-format, cpplint, markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python for cpplint
        run: |
          python3 -m pip install --upgrade pip
          pip3 install cpplint markdownlint-cli

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Check C++ formatting with clang-format
        # This checks that files are formatted; if not, it errors.
        run: |
          FILES="SessionManager.cpp"
          for file in $FILES; do
            clang-format --dry-run --Werror $file
          done

      - name: Run cpplint on C++ file
        run: |
          cpplint SessionManager.cpp

      - name: Run markdownlint on Markdown files
        run: |
          # install markdownlint-cli globally is above; you can customize patterns
          markdownlint '**/*.md'
