name: Lint C++ Code

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '.clang-format'
  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '.clang-format'

jobs:
  lint:
    name: Run cpplint and clang-format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip clang-format
          pip3 install cpplint

      - name: Run cpplint
        run: |
          cpplint --recursive --filter=-legal/copyright .

      - name: Check clang-format
        run: |
          FILES=$(find . -regex '.*\.\(cpp\|hpp\)' -not -path "./build/*")
          for file in $FILES; do
            clang-format --dry-run --Werror $file
          done
