name: CI – Lint C++ & Markdown on Session_Management Branch

on:
  push:
    branches:
      - Session_Management
    paths:
      - 'SessionManager.cpp'
      - '**/*.md'
      - '.clang-format'
  pull_request:
    branches:
      - Session_Management
    paths:
      - 'SessionManager.cpp'
      - '**/*.md'
      - '.clang-format'

jobs:
  lint:
    name: Lint C++ & Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install clang-format
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      # Setup Python & install cpplint
      - name: Setup Python for cpplint
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cpplint
        run: |
          python3 -m pip install --upgrade pip
          pip3 install cpplint

      # Setup Node.js & install markdownlint-cli
      - name: Setup Node.js for markdownlint
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdownlint-cli
        run: |
          npm install -g markdownlint-cli

      # 1. Check C++ formatting
      - name: Check formatting with clang-format
        run: |
          FILES="SessionManager.cpp"
          for file in $FILES; do
            if [ -f "$file" ]; then
              echo "Checking format: $file"
              clang-format --dry-run --Werror "$file"
            fi
          done

      # 2. Run cpplint
      - name: Run cpplint on C++ files
        run: |
          FILES="SessionManager.cpp"
          for file in $FILES; do
            if [ -f "$file" ]; then
              echo "Linting: $file"
              cpplint "$file"
            fi
          done

      # 3. Lint Markdown files
      - name: Lint Markdown files
        run: |
          echo "Linting Markdown files..."
          markdownlint-cli "**/*.md"

      - name: Auto-fix formatting with clang-format
        run: |
          FILES="SessionManager.cpp"
          for file in $FILES; do
            if [ -f "$file" ]; then
              clang-format -i "$file"
            fi
          done
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "style: Auto-format using clang-format" || echo "No changes to commit"
          git push || echo "No changes to push"

