name: CI Format and Lint for SessionManager.cpp

on:
  push:
    paths:
      - 'SessionManager.cpp'
  workflow_dispatch:

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
          python3 -m pip install --upgrade pip
          pip install cpplint

      - name: Run clang-format check
        run: clang-format --dry-run --Werror SessionManager.cpp

      - name: Run cpplint check (filtered rules)
        run: cpplint --filter=-legal/copyright,-whitespace/braces,-whitespace/indent,-runtime/references SessionManager.cpp
