name: Lint Check for SessionManagement

on:
  push:
    paths:
      - 'SessionManagement.cpp'
      - 'SessionManagement.h'

jobs:
  lint:
    name: Run cpplint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install cpplint
      run: pip install cpplint

    - name: Run cpplint on SessionManagement files
      run: |
        cpplint SessionManagement.cpp
        cpplint SessionManagement.h
