name: CI for playermanager

on:
  push:
    paths:
      - 'playermanager.cpp'
      - 'Headers/playermanager.h'

jobs:
  cpplint-check:
    name: Run cpplint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint on playermanager.cpp
        run: cpplint game.cpp

      - name: Run cpplint on Headers/playermanager.h
        run: cpplint Headers/playermanager.h
