name: CI Lint for C++ files

on:
  push:
    branches:
      - final           # Only on final branch
    paths:
      - 'final/**'      # Only if files in final/ change
  workflow_dispatch:     # Allow manual trigger

jobs:
  cpplint-check:
    name: CPPLint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List changed files
        run: |
          echo "Changed files in this push:"
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            git diff --name-only HEAD^ HEAD
          else
            git ls-tree --name-only -r HEAD
          fi

      - name: Set up Python and install cpplint
        run: |
          python3 -m pip install --upgrade pip
          pip install cpplint

      - name: Run cpplint on changed C/C++ files under final/ (excluding json.hpp)
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            CHANGED=$(git diff --name-only HEAD^ HEAD)
          else
            CHANGED=$(git ls-tree --name-only -r HEAD)
          fi
          echo "All changed files:"
          echo "$CHANGED"
          for file in $CHANGED; do
            case "$file" in
              final/json.hpp)
                echo "Skipping cpplint for $file"
                continue
                ;;
              final/*.cpp|final/*.cc|final/*.c|final/*.h|final/*.hpp)
                if [ -f "$file" ]; then
                  echo "Running cpplint on $file"
                  cpplint --filter=-legal/copyright,-whitespace/braces,-whitespace/indent,-runtime/references "$file"
                fi
                ;;
              *)
                ;;
            esac
          done
