name: CI for SessionManagement

on:
  push:
    paths:
      - 'Authentication.cpp'
      - 'Headers/Authentication.h'

jobs:
  cpplint-check:
    name: Run cpplint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint on Authentication.cpp
        run: cpplint Authentication.cpp

      - name: Run cpplint on Headers/Authentication.h
        run: cpplint Headers/Authentication.h
